#!/bin/sh

GPG=/usr/bin/gpg

while getopts "o:" opt; do
    case $opt in
        o)
            OPATH=$OPTARG
            ;;
        \?)
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument" >&2
            exit 1;
            ;;
    esac
done

shift $((OPTIND-1))
FPATH=$1
if [ -z $FPATH ] ; then
    echo no file given to decrypt, exiting! >&2
    exit 1
elif [ ! -r $FPATH ] ; then
    echo file $FPATH not readable, exiting! >&2
    exit 1
elif [ ! -f $FPATH ] ; then
    echo $FPATH is not a file, exiting! >&2
    exit 1
fi

if [ ! -z $OPATH ] ; then
    if  [ ! -d $OPATH ] ; then
        echo $OPATH is not a directory, exiting! >&2
        exit 1
    fi
else
    OPATH="."
fi

OPATH="${OPATH%/}/"

FILENAME=$(basename $FPATH)
NEWFILENAME=${FILENAME%.*}

gpg -o ${OPATH}${NEWFILENAME} $FPATH

if [ $? != 0 ] ; then
    exit 1
fi

echo "\n${OPATH}${NEWFILENAME}\n"
