#!/bin/bash
#
# opendec - decrypt a file, open it and then remove it
#
# All parameters are directly passed to gpgdecrypt

FILE=$(gpgdecrypt $@)
if [ $? == 1 ] ; then
    exit 1
fi
gnome-open $FILE
sleep 2
srm -v $FILE
