#!/usr/bin/env bash

set -euo pipefail

function get_volume {
    pactl get-sink-volume "$(pactl get-default-sink)" | awk -W posix '/^Volume: / {gsub("%,?", ""); print $5; exit}'
}

function get_icon {
    if pactl get-sink-mute @DEFAULT_SINK@ | grep -q '^Mute: yes$' ; then
        echo "audio-volume-muted-symbolic"
        return
    fi
    if [ "${1:-0}" -le 20 ] ; then
        echo "audio-volume-low-symbolic"
        return
    fi
    if [ "${1:-0}" -le 80 ] ; then
        echo "audio-volume-medium-symbolic"
        return
    fi
    echo "audio-volume-high-symbolic"
}

TIMEOUT=1000

case ${1:-} in
    up)
        VOL=$(get_volume)
        INC=${2:-5}
        TARGET_VOL=$((VOL + INC))
        if (( TARGET_VOL > 100 )) ; then
            TARGET_VOL=100
        fi
        pactl set-sink-volume @DEFAULT_SINK@ "${TARGET_VOL}%"
        ICON=$(get_icon "${VOL}")
        VOL=$(get_volume)
        dunstify -t "${TIMEOUT}" -i "${ICON}" -r 5752 -u normal -h "int:value:${VOL}" "Volume: ${VOL}%"
        ;;
    down)
        INC=${2:-5}
        pactl set-sink-volume @DEFAULT_SINK@ "-${INC}%"
        VOL=$(get_volume)
        ICON=$(get_icon "${VOL}")
        dunstify -t "${TIMEOUT}" -i "${ICON}" -r 5752 -u normal -h "int:value:${VOL}" "Volume: ${VOL}%"
        ;;
    mute)
        pactl set-sink-mute @DEFAULT_SINK@ toggle
        VOL=$(get_volume)
        ICON=$(get_icon "${VOL}")
        dunstify -t "${TIMEOUT}" -i "${ICON}" -r 5752 -u normal -h "int:value:${VOL}" "Volume: ${VOL}%"
        ;;
    *)
        echo "usage: $(basename "$0") up [N] | down [N] | mute"
esac
