#!/bin/sh
#
# watch-website-changes check a web page for changes
# 
# Usage:
# $ watch-website-changes www.reddit.com
# 
# Prints nothing when the page hasn't changed, a message and the URL otherwise.

MD5SUM=/usr/bin/md5sum
CURL=/usr/bin/curl
OLD=""
URL=$1

if [[ -z $URL ]] ; then
    echo "You must supply a URL to watch as first parameter"
    exit 1
fi

diff() {
    NEW=`curl -s $URL | $MD5SUM`
    sed -i -e "s/^OLD=.*/OLD=\"$NEW\"/" $0
    if [[ $OLD == $NEW ]] ; then
        return 1
    else
        return 0
    fi
}

if diff ; then
    echo "New changes available: $URL"
fi
