#!/bin/bash
#
# watch-website-changes check a web page for changes
# 
# Usage:
# $ watch-website-changes www.reddit.com
# 
# Prints nothing when the page hasn't changed, a message and the URL otherwise.

OLD=""
URL=$1

if [[ -z $URL ]] ; then
    echo "You must supply a URL to watch as first parameter"
    exit 1
fi

diff() {
    TMP=/tmp/website-watcher.out
    touch $TMP
    curl -o $TMP -fs $URL
    if [[ $? != 0 ]] ; then
        return 1
    fi
    NEW=`cat $TMP | md5sum`
    sed -i -e "s/^OLD=.*/OLD=\"$NEW\"/" $0
    rm $TMP
    if [[ $OLD == $NEW ]] ; then
        return 1
    else
        return 0
    fi
}

if diff ; then
    echo "New changes available: $URL"
fi
