---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-repository-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git
spec:
  selector:
    matchLabels:
      app: gitserver
  template:
    metadata:
      labels:
        app: gitserver
    spec:
      containers:
        - image: docker.io/makkes/gitserver:v0.1.0
          name: server
          env:
            - name: BOOTSTRAP_GIT_PASSWORD
              value: git123
          volumeMounts:
            - mountPath: /srv/git
              name: git-repository-storage
      volumes:
        - persistentVolumeClaim:
            claimName: git-repository-storage
          name: git-repository-storage
---
apiVersion: v1
kind: Service
metadata:
  name: git
spec:
  ports:
    - port: 80
  selector:
    app: gitserver
